name: testes api + contrato

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Instalar dependências
        run: npm install

      - name: Rodar testes Cypress
        continue-on-error: true
        run: npx cypress run

      - name: Rodar testes de contrato
        continue-on-error: true
        run: |
          docker compose up -d
          sleep 10
          npm run test:consumer
          npm run test:provider
          docker compose down

      - name: Publicar resultados no GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./cypress